- name: Deploy Artifact to OpenShift
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Fetch artifact from JFrog Artifactory
      command: curl -u "{{ ARTIFACTORY_USERNAME }}:{{ ARTIFACTORY_PASSWORD }}" -o artifact.ext "{{ ARTIFACT_URL }}"

    - name: Log in to OpenShift
      command: oc login <your-openshift-cluster-url> --token="{{ OPENSHIFT_PASSWORD }}"
      
    - name: Deploy artifact to OpenShift
      command: oc apply -f artifact.ext
