name: Deploy Artifact to OpenShift Workflow

on:
  push:
    branches:
        - main 
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' 

jobs:
    deploy-openshift:
        runs-on: ubuntu-latest
        steps:
            - name: 'Clone the repository.'
              uses: actions/checkout@v2
            - name: 'Deploy Artifact to OpenShift'
              uses: ./.github/actions/deploy-artifact-to-openshift #uses the deployment action
              with:
                environment: prod #change this according to the environment
                artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
                artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
                artifact-url: ${{ secrets.ARTIFACTORY_URL }}
                openshift-username: ${{ secrets.OPENSHIFT_USERNAME }}
                openshift-password: ${{ secrets.OPENSHIFT_PASSWORD }}
                
